services:
  omas_interface:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_fastapi
    ports:
        - '8000:8000'
    env_file:
        - .env
    volumes:
        - './app:/app'
        - '.env:/app/.env'
    working_dir: /app
    command: "fastapi run main.py"
