CREATE EXTENSION vector;

CReATE TABLE models_types (
  id SMALLINT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(30) NOT NULL,

  PRIMARY KEY(id)
);

CREATE TABLE agents (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  type_id SMALLINT NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY(id),
  CONSTRAINT fk_type_id FOREIGN KEY(type_id) REFERENCES models_types(id)
);

INSERT INTO models_types (name) VALUES ('netlogo');

CREATE TABLE m1 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE m2 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE m3 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alive_agents (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  model VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE router (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
