CREATE TABLE m1 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE m2 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE m3 (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alive_agents (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  model VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE router (
  id BIGSERIAL PRIMARY KEY,
  agent_id INTEGER NOT NULL,
  data VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  asl_file_path VARCHAR(255) NOT NULL DEFAULT '',
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
