FROM python:3.12.2-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl git && \
	curl -O https://repo.anaconda.com/archive/Anaconda3-2025.06-0-Linux-x86_64.sh

RUN bash Anaconda3-2025.06-0-Linux-x86_64.sh -b -p /opt/anaconda && \
    rm Anaconda3-2025.06-0-Linux-x86_64.sh

ENV PATH=/opt/anaconda/bin:$PATH

RUN conda tos accept --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --channel https://repo.anaconda.com/pkgs/r && \
    conda create -n tinytroupe python=3.12 -y

ENV PATH=/opt/anaconda/envs/tinytroupe/bin:$PATH

RUN pip install git+https://github.com/microsoft/TinyTroupe.git@main

COPY . .
