FROM python:3.12.2-slim

WORKDIR /register

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./register/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .
